[project]
name = "leetcode-py"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[build-system]
requires = ["uv_build>=0.9.21,<0.10.0"]
build-backend = "uv_build"

[tool.pytest.ini_options]
python_files = "tests/*.py"

[dependency-groups]
dev = ["pytest>=8.4.2"]
